(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (fill-column-indicator yasnippet-snippets yapfify yaml-mode xterm-color writeroom-mode winum which-key wgrep web-mode web-beautify vterm uuidgen utop use-package unfill tuareg treemacs-projectile treemacs-magit treemacs-evil toml-mode toc-org terminal-here tagedit symbol-overlay string-inflection spaceline-all-the-icons smex slim-mode shell-pop seeing-is-believing scss-mode sass-mode rvm ruby-tools ruby-test-mode ruby-refactor ruby-hash-syntax rubocopfmt rubocop rspec-mode robe rjsx-mode restart-emacs rbenv ranger rake racer pytest pyim pyenv-mode py-isort pug-mode prettify-utils prettier-js popwin pippel pipenv pip-requirements persp-mode pdf-tools password-generator paradox pangu-spacing overseer org-pomodoro org-mime org-cliplink open-junk-file ocp-indent ob-elixir nodejs-repl nameless mwim mvn multi-term move-text mmm-mode minitest meghanada maven-test-mode markdown-toc magit-svn macrostep lsp-ui lsp-treemacs lsp-python-ms lsp-java live-py-mode link-hint json-navigator json-mode js2-refactor js-doc ivy-yasnippet ivy-xref ivy-rtags ivy-purpose ivy-hydra insert-shebang indent-guide importmagic impatient-mode ibuffer-projectile hybrid-mode hungry-delete hl-todo highlight-parentheses highlight-numbers groovy-mode groovy-imports gradle-mode google-c-style golden-ratio godoctor go-tag go-rename go-impl go-guru go-gen-test go-fill-struct go-eldoc gnuplot gitignore-templates gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link git-gutter-fringe+ fuzzy font-lock+ flyspell-correct-ivy flycheck-ycmd flycheck-rust flycheck-rtags flycheck-pos-tip flycheck-package flycheck-ocaml flycheck-mix flycheck-credo flycheck-bashate flx fish-mode find-by-pinyin-dired expand-region evil-visualstar evil-visual-mark-mode evil-tutor evil-textobj-line evil-surround evil-org evil-numbers evil-nerd-commenter evil-matchit evil-magit evil-lion evil-iedit-state evil-goggles evil-escape evil-cleverparens evil-anzu eval-sexp-fu eshell-z eshell-prompt-extras esh-help emojify emoji-cheat-sheet-plus emmet-mode elisp-slime-nav editorconfig eaf dune dumb-jump dracula-theme dotenv-mode doom-modeline diminish diff-hl devdocs dap-mode cython-mode cquery cpp-auto-include counsel-projectile counsel-css company-ycmd company-web company-statistics company-shell company-rtags company-reftex company-lsp company-go company-emoji company-c-headers company-box company-auctex company-anaconda column-enforce-mode clang-format chruby chinese-conv centered-cursor-mode ccls cargo bundler browse-at-remote blacken bind-map auto-yasnippet auto-highlight-symbol auto-compile all-the-icons-dired alchemist aggressive-indent ace-pinyin ace-link))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(all-the-icons-dired-dir-face ((t (\` (:foreground (\, (face-background (quote default)))))))))
